- id: '1705440749668'
  alias: 'PC : Eteindre si faible consommation'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.pc_consommation_actuelle
    below: 1
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.pc
    data: {}
  mode: single
- id: '1705440915802'
  alias: 'PC : Allumer automatiquement au réveil'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: switch.pc
    state: 'off'
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.pc
  mode: single
- id: '1705441264950'
  alias: 'Vacation Mode : Activer'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.galedrim
    from: home
    to: not_home
    for:
      hours: 24
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - data: {}
    target:
      entity_id: input_boolean.vacation_mode
    action: input_boolean.turn_on
  - metadata: {}
    data:
      title: VACATION MODE ACTIVE
    action: notify.mobile_app_iphone_de_paulj
  mode: single
- id: '1705441394367'
  alias: 'Vacation Mode : Désactiver'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.galedrim
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - metadata: {}
    data: {}
    target:
      entity_id: input_boolean.vacation_mode
    action: input_boolean.turn_off
  - metadata: {}
    data:
      title: VACATION MODE DESACTIVE
    action: notify.mobile_app_iphone_de_paulj
  mode: single
- id: '1705441556131'
  alias: 'Aspirateur : Nettoyage Démarré'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.rockrobo
    from: docked
    to: cleaning
  condition: []
  action:
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: '{{ now().isoformat() }}'
    target:
      entity_id: input_datetime.vacuum_on
  - condition: state
    entity_id: person.galedrim
    state: not_home
  - service: notify.mobile_app_iphone_de_paulj
    data:
      title: Robot Aspirateur
      message: Robot Aspirateur a commencé à nettoyer
  mode: single
- id: '1705441783755'
  alias: 'Aspirateur : Nettoyage Terminé'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.rockrobo
    from: returning
    to: docked
  condition: []
  action:
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.cleaned_today
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: '{{ now().isoformat() }}'
    target:
      entity_id: input_datetime.vacuum_off
  - condition: state
    entity_id: person.galedrim
    state: not_home
  - service: notify.mobile_app_iphone_de_paulj
    metadata: {}
    data:
      message: '"Nettoyage terminé"'
      title: Robot Aspirateur
  mode: single
- id: '1705441984424'
  alias: 'Aspirateur : Démarrer si absent'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.galedrim
    from: home
    to: not_home
  - platform: time_pattern
    hours: /1
  condition:
  - condition: time
    after: '16:00:00'
    before: '21:00:00'
  - condition: state
    entity_id: binary_sensor.vacuum_day
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacuum_cleaned_today
    state: 'off'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  action:
  - service: script.1705442251155
    metadata: {}
    data: {}
  mode: single
- id: '1705442385080'
  alias: 'Aspirateur : Reset'
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_cleaned_today
    state: 'on'
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.cleaned_today
  mode: single
- id: '1705442543425'
  alias: 'PC : Extinction Effectuée'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.pc
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: '{{ now().isoformat() }}'
    target:
      entity_id: input_datetime.pc_off
  mode: single
- id: '1705442602863'
  alias: 'PC : Allumage Effectué'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.pc
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: '{{ now().isoformat() }}'
    target:
      entity_id: input_datetime.pc_on
  mode: single
- id: '1705442996063'
  alias: 'Lumières : Eteindre si absent'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.galedrim
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: time_pattern
    hours: /1
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: light.turn_off
    target:
      entity_id: light.salon
    data: {}
  mode: single
- id: '1705443451025'
  alias: 'Réveil : Allumer'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states("sensor.time")[0:5] == states("sensor.ten_minutes_before_alarm")
      }}'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_clock
    state: 'on'
  - condition: state
    entity_id: binary_sensor.alarm_day
    state: 'on'
  - condition: state
    entity_id: binary_sensor.someone_in_the_house_in_last_hour
    state: 'on'
  action:
  - metadata: {}
    data: {}
    action: script.allumer_lumiere_graduellement
  - metadata: {}
    data: {}
    action: script.allumer_reveil
  mode: single
- id: '1705444083342'
  alias: 'Réveil : Eteindre automatiquement'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.activity_in_corridor
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  condition:
  - condition: state
    entity_id: light.lampe_chambre
    state: 'on'
  action:
  - data: {}
    action: script.eteindre_lumiere_chambre
  - metadata: {}
    data: {}
    action: script.eteindre_reveil
  - metadata: {}
    data: {}
    target:
      entity_id: script.allumer_nest_mini_graduellement
    action: script.turn_off
  mode: single
- id: '1705444466577'
  alias: 'Lumières : Allumer si porte ouverte'
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 94560330ef87779919f3d612f5bd0018
    entity_id: 5b81079f7f8a29b8b259add1213ed57b
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  - condition: state
    entity_id: binary_sensor.someone_in_the_house_in_last_hour
    state: 'off'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.salon
  mode: single
- id: '1705445702418'
  alias: 'Cafetière : Allumer automatiquement au réveil'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.coffeemaker_started_today
    state: 'off'
  action:
  - service: script.allumer_cafetiere
    data: {}
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.coffeemaker_started_today
  mode: single
- id: '1705445987483'
  alias: 'Sleep Mode : Activer'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.activity_in_bedroom
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: time
    after: '20:00:00'
    before: 07:00:00
  action:
  - target:
      entity_id: input_boolean.sleep_mode
    data: {}
    action: input_boolean.turn_on
  mode: single
- id: '1705446144156'
  alias: 'Cafetière : Reset'
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.coffeemaker_started_today
  mode: single
- id: '1708603692401'
  alias: 'Lumières : Eteindre automatiquement'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    to: 'on'
    from: 'off'
  - platform: state
    entity_id:
    - binary_sensor.activity_in_living_room
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - metadata: {}
    data: {}
    target:
      entity_id: light.salon
    action: light.turn_off
  mode: single
- id: '1720722772151'
  alias: 'Sleep Mode : Désactiver'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.activity_in_corridor
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: time
    after: 07:00:00
    before: '20:00:00'
  action:
  - target:
      entity_id: input_boolean.sleep_mode
    data: {}
    action: input_boolean.turn_off
  mode: single
- id: '1724455110657'
  alias: 'Réveil : Notifier si absent'
  description: ''
  trigger:
  - platform: device
    device_id: 8e10f31f24c573de482e169a2eadbde8
    domain: media_player
    entity_id: d73c395bbc96fc47878006d5f8bb3e44
    type: playing
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  action:
  - action: notify.mobile_app_iphone_de_paulj
    data:
      message: ALARME ENCLENCHE
  mode: single
