- id: '1705440749668'
  alias: 'PC : Eteindre si faible consommation'
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.pc_consommation_actuelle
    below: 1
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.pc
    data: {}
  mode: single
- id: '1705440915802'
  alias: 'PC : Allumer au réveil'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    to: 'off'
    from: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: switch.pc
    state: 'off'
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.pc
  mode: single
- id: '1705441264950'
  alias: 'Vacation Mode : Démarrer Automatiquement'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.galedrim
    from: home
    to: not_home
    for:
      hours: 24
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.vacation_mode
  - service: notify.mobile_app_iphone_de_paulj
    metadata: {}
    data:
      title: Vacation Mode
      message: Personne dans la maison depuis24h, changement en "Vacation Mode"
  mode: single
- id: '1705441394367'
  alias: 'Vacation Mode : Eteindre automatiquement'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.galedrim
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.vacation_mode
  - service: notify.mobile_app_iphone_de_paulj
    metadata: {}
    data:
      title: Vacation Mode
      message: Bon Retour ! Arrêt du "Vacation Mode"
  mode: single
- id: '1705441556131'
  alias: 'Aspirateur : Nettoyage Démarré'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.rockrobo
    from: docked
    to: cleaning
  condition: []
  action:
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: '{{ now().isoformat() }}'
    target:
      entity_id: input_datetime.vacuum_on
  - service: notify.mobile_app_iphone_de_paulj
    data:
      title: Robot Aspirateur
      message: Robot Aspirateur a commencé à nettoyer
  mode: single
- id: '1705441783755'
  alias: 'Aspirateur : Nettoyage Terminé'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - vacuum.rockrobo
    from: returning
    to: docked
  condition: []
  action:
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.cleaned_today
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: '{{ now().isoformat() }}'
    target:
      entity_id: input_datetime.vacuum_off
  - service: notify.mobile_app_iphone_de_paulj
    metadata: {}
    data:
      message: '"Nettoyage terminé"'
      title: Robot Aspirateur
  mode: single
- id: '1705441984424'
  alias: 'Aspirateur : Démarrer si absent'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.galedrim
    from: home
    to: not_home
  - platform: time_pattern
    hours: /1
  condition:
  - condition: time
    after: '16:00:00'
    before: '21:00:00'
  - condition: state
    entity_id: binary_sensor.vacuum_day
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacuum_cleaned_today
    state: 'off'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  action:
  - service: script.1705442251155
    metadata: {}
    data: {}
  mode: single
- id: '1705442385080'
  alias: 'Aspirateur : Nettoyage Reset'
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition:
  - condition: state
    entity_id: input_boolean.vacuum_cleaned_today
    state: 'on'
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.cleaned_today
  mode: single
- id: '1705442543425'
  alias: 'PC : Extinction Effectuée'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.pc
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: '{{ now().isoformat() }}'
    target:
      entity_id: input_datetime.pc_off
  mode: single
- id: '1705442602863'
  alias: 'PC : Démarrage Effectué'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.pc
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: input_datetime.set_datetime
    metadata: {}
    data:
      datetime: '{{ now().isoformat() }}'
    target:
      entity_id: input_datetime.pc_on
  mode: single
- id: '1705442996063'
  alias: 'Lumières : Eteindre si absent'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.galedrim
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - platform: time_pattern
    hours: /1
  condition:
  - condition: state
    entity_id: binary_sensor.no_one_home
    state: 'on'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: light.turn_off
    target:
      entity_id: light.salon
    data: {}
  mode: single
- id: '1705443451025'
  alias: 'Réveil : Allumer Nest et Lumières Graduellement'
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states("sensor.time")[0:5] == states("sensor.ten_minutes_before_alarm")
      }}'
  condition:
  - condition: state
    entity_id: input_boolean.alarm_clock
    state: 'on'
  - condition: state
    entity_id: input_boolean.alarm_sounded_today
    state: 'off'
  - condition: state
    entity_id: binary_sensor.alarm_day
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  action:
  - service: script.allumer_lumiere_graduellement
    metadata: {}
    data: {}
  - service: script.allumer_reveil
    metadata: {}
    data: {}
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.alarm_sounded_today
  - service: automation.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: automation.reveil_redemarrer_si_pas_debout
  mode: single
- id: '1705444083342'
  alias: 'Réveil : Eteindre si activité dans couloir'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.activity_in_corridor
    to: 'on'
  condition:
  - condition: state
    entity_id: light.lampe_chambre
    state: 'on'
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.chambre_a_coucher
  - service: script.eteindre_reveil
    metadata: {}
    data: {}
  - service: script.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: script.allumer_nest_mini_graduellement
  - service: automation.turn_off
    target:
      entity_id:
      - automation.reveil_redemarrer_si_pas_debout
    data:
      stop_actions: true
  mode: single
- id: '1705444466577'
  alias: 'Lumières : Allumer si porte ouverte'
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 94560330ef87779919f3d612f5bd0018
    entity_id: 5b81079f7f8a29b8b259add1213ed57b
    domain: binary_sensor
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  - condition: state
    entity_id: binary_sensor.someone_in_the_house_in_last_hour
    state: 'off'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.salon
  mode: single
- id: '1705445702418'
  alias: 'Cafetière : Allumer au réveil'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    to: 'off'
    from: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.coffeemaker_started_today
    state: 'off'
  action:
  - service: script.allumer_cafetiere
    data: {}
  - service: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.coffeemaker_started_today
  mode: single
- id: '1705445987483'
  alias: 'Sleep Mode : Démarrer automatiquement'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.activity_in_bedroom
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: time
    after: '21:00:00'
    before: 07:00:00
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.sleep_mode
    data: {}
  mode: single
- id: '1705446144156'
  alias: 'Cafetière : Démarrage Reset'
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.coffeemaker_started_today
  mode: single
- id: '1705503211146'
  alias: 'Sleep Mode : Éteindre automatiquement'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.activity_in_corridor
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: time
    after: 07:00:00
    before: '21:00:00'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.sleep_mode
    data: {}
  mode: single
- id: '1705504657705'
  alias: 'Réveil : Redémarrer toutes les 5 minutes'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: script.allumer_nest_mini_instantanement
    data: {}
  mode: single
- id: '1708603692401'
  alias: 'Lumières : Eteindre si dormir'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    to: 'on'
    from: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.salon
  mode: single
- id: '1717426309232'
  alias: 'Réveil : Démarrage Reset'
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition:
  - condition: state
    entity_id: input_boolean.alarm_sounded_today
    state: 'on'
  action:
  - service: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.alarm_sounded_today
  mode: single
- id: '1717430695623'
  alias: 'Plante : Notification Problème avec Sansevieria'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - plant.sansevieria
    to: problem
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: plant.sansevieria
    state: problem
  action:
  - service: notify.mobile_app_iphone_de_paulj
    metadata: {}
    data:
      title: "Problème Sansevieria \U0001F33F⚠️"
      message: 'Problème sur '
  mode: single
