---
#                   __ _                       _   _
#   ___ ___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __
#  / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \
# | (_| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
#  \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
#                        |___/
#

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Managed via UI
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Inputs
input_boolean: !include includes/input_booleans.yaml
input_datetime: !include includes/input_datetimes.yaml
input_select: !include includes/input_selects.yaml
input_number: !include includes/input_numbers.yaml

# Logging and history
logger: !include includes/logger.yaml

# Others
binary_sensor: !include includes/binary_sensors.yaml
http: !include includes/http.yaml
plant: !include includes/plant.yaml
sensor: !include includes/sensors.yaml
shell_command: !include includes/shell_commands.yaml
