---
views:
- cards:
  - cards:
    - title: Modes
      type: custom:mushroom-title-card
    - cards:
      - entity: person.galedrim
        layout: horizontal
        type: custom:mushroom-entity-card
      - entity: input_boolean.sleep_mode
        layout: horizontal
        name: Nuit
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      type: horizontal-stack
    - cards:
      - entity: input_boolean.guest_mode
        name: Invité
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      - entity: input_boolean.vacation_mode
        name: Vacance
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      type: horizontal-stack
    type: vertical-stack
  - cards:
    - title: Salon
      type: custom:mushroom-title-card
    - cards:
      - entity: light.salon
        name: Lumières
        show_brightness_control: true
        type: custom:mushroom-light-card
        use_light_color: true
      - entity: input_select.living_room_color
        icon_color: accent
        name: Scènes
        secondary_info: none
        tap_action:
          action: call-service
          service: script.1705435245310
          target: {}
        type: custom:mushroom-select-card
      type: horizontal-stack
    - cards:
      - entity: media_player.salon_2
        fill_container: false
        media_controls:
        - on_off
        name: TV
        type: custom:mushroom-media-player-card
        volume_controls:
        - volume_mute
      - entity: input_select.tv_app
        icon_color: deep-purple
        name: Chaînes
        secondary_info: none
        tap_action:
          action: call-service
          service: script.demarrer_chaines_tv
          target: {}
        type: custom:mushroom-select-card
      type: horizontal-stack
    type: vertical-stack
  - cards:
    - title: Chambre
      type: custom:mushroom-title-card
    - cards:
      - entity: media_player.chambre
        media_controls: []
        tap_action:
          action: toggle
        type: custom:mushroom-media-player-card
        volume_controls: []
      - collapsible_controls: false
        entity: light.chambre_a_coucher
        fill_container: false
        name: Lumières
        show_brightness_control: false
        show_color_control: false
        show_color_temp_control: false
        type: custom:mushroom-light-card
        use_light_color: false
      type: horizontal-stack
    - cards:
      - entity: input_boolean.alarm_clock
        name: Alarme
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      - entity: input_datetime.alarm_clock
        icon_color: deep-purple
        name: Heure
        primary_info: state
        secondary_info: name
        type: custom:mushroom-entity-card
      type: horizontal-stack
    - cards:
      - entity: input_boolean.alarm_monday
        fill_container: false
        icon_type: icon
        layout: vertical
        name: L
        primary_info: none
        secondary_info: name
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      - entity: input_boolean.alarm_tuesday
        icon_type: icon
        layout: vertical
        name: M
        primary_info: none
        secondary_info: name
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      - entity: input_boolean.alarm_wednesday
        icon_type: icon
        layout: vertical
        name: M
        primary_info: none
        secondary_info: name
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      - entity: input_boolean.alarm_thursday
        icon_type: icon
        layout: vertical
        name: J
        primary_info: none
        secondary_info: name
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      - entity: input_boolean.alarm_friday
        icon_type: icon
        layout: vertical
        name: V
        primary_info: none
        secondary_info: name
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      - entity: input_boolean.alarm_saturday
        icon_type: icon
        layout: vertical
        name: S
        primary_info: none
        secondary_info: name
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      - entity: input_boolean.alarm_sunday
        icon_type: icon
        layout: vertical
        name: D
        primary_info: none
        secondary_info: name
        tap_action:
          action: toggle
        type: custom:mushroom-entity-card
      type: horizontal-stack
    type: vertical-stack
  - cards:
    - title: Equipements
      type: custom:mushroom-title-card
    - cards:
      - icon: mdi:coffee-maker
        primary: Cafetière
        secondary: '{{ states("input_datetime.coffeemaker_on")[0:5]  }}

          '
        tap_action:
          action: call-service
          service: script.allumer_cafetiere
          target: {}
        type: custom:mushroom-template-card
      - entity: sensor.marin_echo_next_timer
        name: Echo
        type: custom:mushroom-entity-card
      type: horizontal-stack
    - cards:
      - double_tap_action:
          action: none
        entity: switch.pc
        hold_action:
          action: none
        tap_action:
          action: call-service
          service: switch.turn_on
          target:
            entity_id: switch.pc
        type: custom:mushroom-entity-card
      - entity: binary_sensor.rpi_power_status
        name: Serveur
        type: custom:mushroom-entity-card
      type: horizontal-stack
    type: vertical-stack
  - cards:
    - title: Température
      type: custom:mushroom-title-card
    - animated_icon: false
      date_pattern: cccc, d.MM.yy
      entity: weather.forecast_maison
      hide_forecast_section: true
      hide_today_section: false
      locale: fr-FR
      sun_entity: sun.sun
      time_format: 24
      time_pattern: HH:mm
      type: custom:clock-weather-card
      weather_icon_type: fill
    - cards:
      - color_thresholds:
        - color: '#f39c12'
          value: 18
        - color: '#d35400'
          value: 19
        - color: '#c0392b'
          value: 20
        entities:
        - sensor.meter_plus_857f
        name: Temp. Chambre
        show:
          icon: false
        type: custom:mini-graph-card
      - color_thresholds:
        - color: '#f39c12'
          value: 40
        - color: '#d35400'
          value: 50
        - color: '#c0392b'
          value: 60
        entities:
        - sensor.meter_plus_857f_humidite
        name: Hum. Chambre
        show:
          icon: false
        type: custom:mini-graph-card
      type: horizontal-stack
    type: vertical-stack
  - cards:
    - title: Aspirateur
      type: custom:mushroom-title-card
    - cards:
      - commands:
        - start_pause
        - return_home
        entity: vacuum.rockrobo
        name: Robot
        primary_info: state
        secondary_info: none
        type: custom:mushroom-vacuum-card
      - entity: input_select.vacuum_zone
        icon: mdi:vacuum
        icon_color: deep-purple
        name: Zone
        secondary_info: none
        tap_action:
          action: call-service
          service: script.test
          target: {}
        type: custom:mushroom-select-card
      type: horizontal-stack
    - cards:
      - entity: binary_sensor.vacuum_day
        name: Nettoyage
        type: custom:mushroom-entity-card
      - double_tap_action:
          action: none
        entity: input_datetime.vacuum_off
        hold_action:
          action: none
        icon: mdi:clock
        icon_color: ''
        primary: Historique
        secondary: '{{ ((as_timestamp(now()) - as_timestamp(states("input_datetime.vacuum_off",
          1))) / 86400) | int(0) }} jours'
        tap_action:
          action: none
        type: custom:mushroom-template-card
      type: horizontal-stack
    type: vertical-stack
  title: Home
